export const STRIPE = {
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
    'pk_test_51KAM5FJSrWpQVbhlHiLvidslxcmefhBtvGaRtNhPROXAaMN1HVcqOE2DgrAP4K4KULKsPiwY14skB6htNFbV4GeP00EvdJB0Uh',
  STRIPE_SECRET_KEY:
    'sk_test_51KAM5FJSrWpQVbhlykbwmLndSvrs57ADbt3MA2KD3fyp4Y2OQKbvZWDJiE9QW6CWCNWa5WOC97RCAKG9vbD2GujQ00BYFVgaBL',
  STRIPE_PAYMENT_DESCRIPTION: 'Software development services',
  STRIPE_WEBHOOK_SECRET: 'whsec_1234',
};
